"""Create Game Model

Revision ID: b0b630429dfa
Revises: e50a86cf55de
Create Date: 2023-04-17 14:00:02.483894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b630429dfa'
down_revision = 'e50a86cf55de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
